# Streamlit Secrets設定
# このファイルは.gitignoreに追加して、リポジトリにプッシュされないようにしてください

# Google APIキーの設定
GOOGLE_API_KEY = "YOUR_API_KEY_HERE"

# 他の設定値があれば追加

[general]
disableAnalytics = true
disableTelemetry = true

[browser]
gatherUsageStats = false

[mapbox]
token = "" 