[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[server]
maxUploadSize = 200
enableCORS = true
enableXsrfProtection = true
headless = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[deprecation]
showfileUploaderEncoding = false 